import Head from 'next/head';
import styles from '@/styles/Home.module.css';

import { add, minus } from '@packages/my-lib';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>20 + 10 : {add(20, 10)}</p>
        <p>20 - 10 : {minus(20, 10)}</p>
      </main>
    </>
  );
}
